# Change these first
owner: Der-Reiskoch # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Der Reiskoch
    url: https://der.reisko.ch/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: hhttps://der-reiskoch.github.io/upptime/logo.svg
  name: Der Reiskoch Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page for "Der Reiskoch". [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://der-reiskoch.github.io/upptime/der-reiskoch-theme.css   
      
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
