# Change these first
owner: Der-Reiskoch # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://www.der-reiskoch.de
  - name: Comments Service
    url: https://kommentare.koch-reis.de/
  - name: Media Server 
    url: https://bilder.koch-reis.de/media/1200/1263/buch_und_block.webp
  - name: Resize Image Service
    url: https://api.koch-reis.de/resize/v2/?width=190&src=%2fmedia%2f0900%2f0918%2fnuea_pad_phed_prik_thai_on.jpg
  - name: Pin Generation Service
    url: https://api.koch-reis.de/social-media/v1/?src=reiskoch&format=pin&id=1390&title=Gurkensalat%20nach%20Sichuan%20Art
  - name: Calendar Flyer Service
    url:  https://api.koch-reis.de/flyer/v1/?id=/2026/20260315_celle.jpg
  - name: YouTube Preview Service
    url:  https://api.koch-reis.de/youtube/v1/?file=m_HzLtoRP64.webp

assignees: erich3000
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://der-reiskoch.github.io/foodie_hugo_media/logo.svg
  name: Der Reiskoch - Status Monitoring
  introTitle: Der Reiskoch
  introMessage: Upptime is the open-source uptime monitor and status page, powered entirely by GitHub. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://der.reisko.ch
  themeUrl: https://der-reiskoch.github.io/upptime/reiskoch-theme.css    
      
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
